// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrHt9L1CcR7Es8ouLLwP4a8mNcB5SiC0A',
    appId: '1:205186689138:android:b6046ff8b8625ce4e4baeb',
    messagingSenderId: '205186689138',
    projectId: 'car-rental-app-80bb5',
    storageBucket: 'car-rental-app-80bb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52zFZthEBoFaTZK_vwPOzEfMwUIvvMv8',
    appId: '1:205186689138:ios:4cbb804cd22e4c46e4baeb',
    messagingSenderId: '205186689138',
    projectId: 'car-rental-app-80bb5',
    storageBucket: 'car-rental-app-80bb5.appspot.com',
    iosBundleId: 'com.example.oneCarRentalApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKfvM83krhY9se30hVFjpZkw1BVdXP1Kw',
    appId: '1:205186689138:web:6256c4be870af074e4baeb',
    messagingSenderId: '205186689138',
    projectId: 'car-rental-app-80bb5',
    authDomain: 'car-rental-app-80bb5.firebaseapp.com',
    storageBucket: 'car-rental-app-80bb5.appspot.com',
    measurementId: 'G-JWZ19NZQH7',
  );

}